<?php
return [
 'empresa_master' => [
 'nome_fantasia' => 'EatsFood',
 'razao_social' => 'EatsFood Tecnologia em Alimentação LTDA',
 'cnpj' => '00.000.000/0000-00',
 'email' => 'contato@eatsfood.com.br',
 'telefone' => '(11) 99999-9999',
 ],
 'planos' => [
 'basico' => [
 'nome' => 'Plano Básico',
 'descricao' => 'Ideal para começar',
 'valor_mensal' => 99.90,
 'max_usuarios' => 3,
 'max_produtos' => 50,
 'max_pedidos_mes' => 200,
 'max_filiais' => 1,
 'taxa_transacao_percent' => 3.99,
 'taxa_fixa_pedido' => 0.99,
 'recursos' => [
 'delivery',
 'mesas',
 'caixa',
 'produtos',
 'pedidos'
 ]
 ],
 'profissional' => [
 'nome' => 'Plano Profissional',
 'descricao' => 'Para negócios em crescimento',
 'valor_mensal' => 249.90,
 'max_usuarios' => 10,
 'max_produtos' => 200,
 'max_pedidos_mes' => 1000,
 'max_filiais' => 3,
 'taxa_transacao_percent' => 2.99,
 'taxa_fixa_pedido' => 0.69,
 'recursos' => [
 'delivery',
 'mesas',
 'caixa',
 'produtos',
 'pedidos',
 'garcom',
 'entregadores',
 'clientes',
 'relatorios_basicos'
 ]
 ],
 'premium' => [
 'nome' => 'Plano Premium',
 'descricao' => 'Recursos avançados',
 'valor_mensal' => 499.90,
 'max_usuarios' => 25,
 'max_produtos' => 500,
 'max_pedidos_mes' => 3000,
 'max_filiais' => 10,
 'taxa_transacao_percent' => 1.99,
 'taxa_fixa_pedido' => 0.49,
 'recursos' => [
 'delivery',
 'mesas',
 'caixa',
 'produtos',
 'pedidos',
 'garcom',
 'entregadores',
 'clientes',
 'relatorios_basicos',
 'relatorios_avancados',
 'api',
 'integracao_ifood',
 'integracao_whatsapp',
 'cardapio_digital'
 ]
 ],
 'enterprise' => [
 'nome' => 'Plano Enterprise',
 'descricao' => 'Solução completa e personalizada',
 'valor_mensal' => 999.90,
 'max_usuarios' => 100,
 'max_produtos' => 999999,
 'max_pedidos_mes' => 999999,
 'max_filiais' => 50,
 'taxa_transacao_percent' => 0.99,
 'taxa_fixa_pedido' => 0.29,
 'recursos' => [
 'delivery',
 'mesas',
 'caixa',
 'produtos',
 'pedidos',
 'garcom',
 'entregadores',
 'clientes',
 'relatorios_basicos',
 'relatorios_avancados',
 'relatorios_personalizados',
 'api',
 'app_mobile',
 'integracao_ifood',
 'integracao_uber_eats',
 'integracao_whatsapp',
 'integracao_erp',
 'cardapio_digital',
 'programa_fidelidade',
 'marketing_automatizado',
 'white_label',
 'dominio_personalizado',
 'suporte_prioritario'
 ]
 ]
 ],
 'recursos_disponiveis' => [
 'delivery' => 'Sistema de Delivery',
 'mesas' => 'Gestão de Mesas',
 'caixa' => 'Controle de Caixa',
 'produtos' => 'Cadastro de Produtos',
 'pedidos' => 'Gestão de Pedidos',
 'garcom' => 'Modo Garçom',
 'entregadores' => 'Gestão de Entregadores',
 'clientes' => 'Cadastro de Clientes',
 'relatorios_basicos' => 'Relatórios Básicos',
 'relatorios_avancados' => 'Relatórios Avançados',
 'relatorios_personalizados' => 'Relatórios Personalizados',
 'api' => 'API de Integração',
 'app_mobile' => 'Aplicativo Mobile',
 'integracao_ifood' => 'Integração iFood',
 'integracao_uber_eats' => 'Integração Uber Eats',
 'integracao_whatsapp' => 'Integração WhatsApp',
 'integracao_erp' => 'Integração com ERP',
 'cardapio_digital' => 'Cardápio Digital QR Code',
 'programa_fidelidade' => 'Programa de Fidelidade',
 'marketing_automatizado' => 'Marketing Automatizado',
 'white_label' => 'Marca Própria (White Label)',
 'dominio_personalizado' => 'Domínio Personalizado',
 'suporte_prioritario' => 'Suporte Prioritário 24/7'
 ],
 'trial' => [
 'duracao_dias' => 15,
 'plano_padrao' => 'profissional',
 ]
];