# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check build files instead.

# For more details on how to configure your build environment visit
# http://www.gradle.org/configure-project-gradle-builds

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for headless machines set %DEFAULT_JVM_OPTS% to use the environment variable.
# default: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/guide/performance-tuning#parallel_builds
org.gradle.parallel=true

# AndroidX package structure to make it clearer which packages are being used in
# your project.
android.useAndroidX=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does nothing about the resources declared in
# dependency libraries -  the reverse, however, is true; each library sees the full, flat
# namespace of all its dependencies.
android.nonTransitiveRClass=true

# Suppress the rendererType attribute in the /manifest/application element
android.suppressUnsupportedCompileSdkWarning=false
