// 1. O bloco pluginManagement DEVE VIR PRIMEIRO
pluginManagement {
    repositories {google()
        mavenCentral()
        gradlePluginPortal()
    }
}

// 2. O bloco dependencyResolutionManagement vem depois
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

// 3. As outras configurações, como nome do projeto e módulos, vêm por último
rootProject.name = "MyDApp"
include ':app'


